import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    // ── Home Page ────────────────────────────────────────────────────
    heroBadge:        "India's Trusted Agricultural Marketplace",
    heroTitle:        "Welcome to",
    fairPrices:       "Agri Connect",
    heroSubtitle:     "Direct trade between farmers, dealers, and customers — no middlemen, no exploitation. Just fair prices and fresh produce.",
    heroBtnFarmer:    "👨‍🌾 I'm a Farmer",
    heroBtnDealer:    "🏢 I'm a Dealer",
    heroBtnCustomer:  "🛒 I'm a Customer",
    builtForYou:      "Built For You",
    whoFor:           "Who is Agri Connect for?",
    whoForSub:        "Whether you grow it, sell it, or eat it — Agri Connect is built for you.",
    forFarmers:       "👨‍🌾 For Farmers",
    forDealers:       "🏢 For Dealers",
    forCustomers:     "🛒 For Customers",
    farmerHeadline:   "Sell your crops directly. Earn what you deserve.",
    farmerSub:        "No middlemen. No exploitation. Connect directly with dealers and customers across India and get the best price for your hard work.",
    farmerBenefits:   ["✅ List your crops in under 2 minutes","✅ Get requests directly from verified dealers & customers","✅ Negotiate prices — full control in your hands","✅ Secure payment — money directly to your account","✅ Track all your sales and earnings in one dashboard","✅ Access government schemes & crop insurance info"],
    farmerCta:        "Join as Farmer",
    farmerStat:       "Average increase in farmer income",
    dealerHeadline:   "Source fresh crops directly from verified farmers.",
    dealerSub:        "Skip the mandis and middlemen. Build direct relationships with farmers. Get consistent quality, fair prices, and reliable supply — all on one platform.",
    dealerBenefits:   ["✅ Browse 1000+ verified farmers across India","✅ Filter by crop, location, price, and quantity","✅ Send bulk requests and negotiate directly","✅ Get real-time market prices and trends","✅ Manage all your supplier relationships","✅ Streamlined payments and transaction history"],
    dealerCta:        "Join as Dealer",
    dealerStat:       "Reduction in procurement cost",
    customerHeadline: "Farm-fresh produce, delivered to your door.",
    customerSub:      "Buy directly from the farmer who grew it. No cold storage, no chemicals. Just pure, fresh produce at prices better than your local market.",
    customerBenefits: ["✅ Order directly from local farmers near you","✅ 100% fresh — harvested and delivered quickly","✅ Better prices than supermarkets","✅ Know exactly which farm your food comes from","✅ Support local farmers with every purchase","✅ Easy ordering — browse, request, receive"],
    customerCta:      "Shop Fresh",
    customerStat:     "Savings compared to market price",
    govSupport:       "Government Support",
    govTitle:         "Government Schemes for Farmers",
    govSub:           "Agri Connect helps farmers discover and access government schemes they are entitled to.",
    checkEligibility: "Check Eligibility",
    schemeNote:       "Agri Connect shows you all schemes you're eligible for based on your profile —",
    schemeFree:       "completely free.",
    discoverSchemes:  "Discover Your Schemes",
    growingTitle:     "Growing Every Day",
    growingSub:       "Real numbers from real farmers across India",
    activeFarmers:    "Active Farmers",
    verifiedDealers:  "Verified Dealers",
    districtsLabel:   "Districts",
    totalTrade:       "Total Traded",
    userStories:      " Real Stories",
    testimonialTitle: "What Our Users Say",
    startTrading:     "Start Trading Today",
    joinCommunity:    "Join 10,000+ farmers and 500+ dealers already growing their business on Agri Connect.",
    registerFree:     "Register Free",
    contactUs:        "Contact Us",
    freeReg:          "Free Registration",
    securePlatform:   "Secure Platform",
    easyToUse:        "Easy to Use",
    farmerFirst:      "Farmer First",
    platform:         "Platform",
    footerPlatformLinks: ["For Farmers","For Dealers","For Customers","Government Schemes","Market Prices"],
    company:          "Company",
    companyLinks:     ["About Us","Contact","FAQ","Privacy Policy","Terms of Service"],
    bridgeGap:        "Bridging the gap between farmers and dealers for a sustainable future.",
    incomeSupport:    "Income Support",
    cropInsurance:    "Crop Insurance",
    equipSubsidy:     "Equipment Subsidy",
    marketAccess:     "Market Access",
    organicFarming:   "Organic Farming",
    farmerLoans:      "Farmer Loans",
    schemeDescs: [
      "₹6,000/year direct income support to eligible farmer families in 3 equal installments.",
      "Crop insurance at low premiums — protect your crops from natural calamities and pests.",
      "Subsidies up to 50-80% on farm machinery and equipment for small & marginal farmers.",
      "Online trading platform connecting APMC mandis — get better prices for your produce.",
      "₹50,000/hectare for 3 years to promote organic farming and get organic certification.",
      "Easy credit up to ₹3 lakh at 4% interest rate for farming needs — seeds, fertilizers, equipment.",
    ],

    // ── Customer Panel ───────────────────────────────────────────────
    welcome: "Welcome",
    freshProduce: "Fresh produce, direct from farmers",
    totalOrders: "Total Orders",
    pending: "Pending",
    completed: "Completed",
    totalSpent: "Total Spent",
    browseProducts: "Browse Products",
    myOrders: "My Orders",
    transactions: "Transactions",
    myProfile: "My Profile",
    freshCrops: "Fresh Available Crops",
    directFarmers: "Direct from farmers near you",
    viewAll: "View All",
    noCrops: "No crops available right now",
    browseAllProducts: "Browse All Products",
    recentOrders: "Recent Orders",
    latestRequests: "Your latest requests to farmers",
    noOrders: "No orders yet",
    browseNow: "Browse Now",
    browseproductrequest: "Browse products and send requests to farmers",
    browseFreshProducts: "Browse Fresh Products",
    productsAvailable: "products available — direct from farmers",
    searchPlaceholder: "Search crop, city, category...",
    all: "All",
    latestFirst: "Latest First",
    refresh: "Refresh",
    noProducts: "No products available right now",
    farmersSoon: "Farmers will list fresh crops soon!",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    mostQuantity: "Most Quantity",
    negotiating: "Negotiating",
    accepted: "Accepted",
    rejected: "Rejected",
    cancelled: "Cancelled",
    noOrdersFound: "No orders found",
    noOrdersMessage: "You haven't placed any orders yet",
    myRequests: "My Requests",
    requestsToFarmers: "requests to farmers",
    searchCropFarmer: "Search crop or farmer...",
    noRequests: "No requests yet",
    browseSendRequest: "Browse products and send requests to farmers!",
    myTransactions: "My Transactions",
    paymentHistory: "Your complete payment history",
    totalPaid: "Total Paid",
    totalReceived: "Total Received",
    totalTransactions: "Total Transactions",
    searchByIdUser: "Search by ID or user...",
    failed: "Failed",
    noTransactionsFound: "No transactions found",
    noPaymentHistory: "No payment history yet",
    marketPrices: "Market Prices",
    liveApmmPrices: "Live APMC mandi prices across India",
    searchMarket: "Search crop, variety, or market...",
    crop: "Crop",
    variety: "Variety",
    grade: "Grade",
    priceQuintal: "Price / Quintal",
    market: "Market",
    date: "Date",
    maharashtraPrices: "prices shown – Maharashtra APMC Markets",
    manageProfile: "Manage your profile and preferences",
    profileInfo: "Profile Information",
    notifications: "Notifications",
    fullName: "Full Name",
    emailAddress: "Email Address",
    city: "City",
    state: "State",
    phone: "Phone",
    address: "Address",
    username: "Username",
    role: "Role",
    editProfile: "Edit Profile",
    accountSecurity: "Account Security",
    accountStatus: "Account Status",
    verified: "Verified",
    changePassword: "Change Password",
    memberSince: "Member Since",
    active: "Active",
    quickActions: "Quick Actions",
    deleteAccount: "Delete Account",
    dangerZone: "Danger Zone",
    deleteAccountMessage: "Permanently delete your account and all data",
    accountVerified: "Your account is verified",
    updatePasswordMsg: "Update your login password anytime",
    deleteAccountMsg: "Permanently delete your account and all data",
    spent: "Spent",
    joined: "Joined",
    notificationPreferences: "Notification Preferences",
    orderUpdates: "Order Updates",
    orderUpdatesDesc: "When order status changes",
    requestResponses: "Request Responses",
    requestResponsesDesc: "When farmers respond to your requests",
    paymentAlerts: "Payment Alerts",
    paymentAlertsDesc: "When payments are processed",
    marketPriceUpdates: "Market Price Updates",
    marketPriceUpdatesDesc: "Daily updates on crop prices",
    newProducts: "New Products",
    newProductsDesc: "When farmers list new products",
    saveSettings: "Save Settings",
    change: "Change",
    delete: "Delete",
    sendRequestsToFarmers: "Send requests to farmers",
    totalApplicants: "Total Applicants",
    totalBudget: "Total Budget",
    applicants: "Applicants",
    approved: "Approved",
    applicationProgress: "Application Progress",
    deadline: "Deadline",
    budget: "Budget",
    coverage: "Coverage",
    launched: "Launched",
    keyFeatures: "Key Features",
    viewDetails: "View Details",
    adjustSearchFilter: "Try adjusting your search or filter to find what you're looking for.",
    createNewScheme: "Create New Scheme",
    accountVerifiedMessage: "Your account is verified",
    updatePasswordText: "Update your login password anytime",
    deleteAccountText: "Permanently delete your account and all data",
    manageFarmerAccount: "Manage your farmer account and settings",
    security: "Security",
    profileInformation: "Profile Information",
    farmSize: "Farm Size",
    farmingExperience: "Farming Experience",
    farmAddress: "Farm Address",
    verifiedAccount: "Verified Account",
    crops: "Crops",
    deals: "Deals",
    revenue: "Revenue",
    notificationSettings: "Notification Settings",
    farmer: "Farmer",
    payments: "Payments",
    managePayments: "Manage your payments to farmers",
    total: "Total",
    exportCSV: "Export CSV",
    payFarmer: "Pay Farmer",
    noPaymentsYet: "No payments yet",
    clickPayFarmer: 'Click "Pay Farmer" to make your first payment',
    businessProfile: "Business Profile",
    manageDealershipProfile: "Manage your dealership profile and business information",
    businessInformation: "Business Information",
    businessName: "Business Name",
    ownerName: "Owner Name",
    contactNumber: "Contact Number",
    businessType: "Business Type",
    gstNumber: "GST Number",
    establishmentYear: "Establishment Year",
    established: "Established",
    licenseNumber: "License Number",
    license: "License",
    businessAddress: "Business Address",
    specialization: "Specialization",
    businessSettings: "Business Settings",
    paymentMethods: "Payment Methods",
    manageAcceptedPayments: "Manage accepted payment methods",
    deliverySettings: "Delivery Settings",
    configureDeliveryLogistics: "Configure delivery and logistics",
    configure: "Configure",
    setup: "Setup",
    tradeAreas: "Trade Areas",
    activeSuppliers: "Active Suppliers",
    monthlyOrders: "Monthly Orders",
    satisfaction: "Satisfaction",
    premiumPartner: "Premium Partner",
    saveProfile: "Save Profile",
    wholesaleDistributor: "Wholesale Distributor",
    grains: "Grains",
    vegetables: "Vegetables",
    cashCrops: "Cash Crops",
    mySuppliers: "My Suppliers",
    manageSuppliers: "Farmers you have deals or requests with",
    addNewSupplier: "Add Supplier",
    totalSuppliers: "Total Suppliers",
    totalValue: "Total Value",
    searchSuppliers: "Search by name, location, crop...",
    allStatus: "All Status",
    inactive: "Inactive",
    mainCrops: "Crops",
    reliability: "Reliability",
    contact: "View Deals",
    orderNow: "Order Now",
    noSuppliersYet: "No suppliers yet",
    noMatchingSuppliers: "No matching suppliers",
    clearSearch: "Try clearing your search",
    goToMarketplace: "Go to Marketplace",
    businessAnalytics: "Business Analytics",
    realTimeInsights: "Real-time insights into your dealership performance",
    lastMonth: "Last Month",
    totalSpentLabel: "Total Spent",
    completedDeals: "Completed Deals",
    farmersSourced: "Farmers Sourced",
    totalRequests: "Total Requests",
    monthlySpending: "Monthly Spending",
    last6Months: "Last 6 months",
    topCropsPurchased: "Top Crops Purchased",
    requestStatus: "Request Status",
    businessInsights: "Business Insights",
    topPurchaseInsight: "Wheat is your top purchase",
    topPurchaseText: "₹1,25,000 spent on Wheat",
    farmersInsight: "12 unique farmers sourced",
    farmersInsightText: "Good supplier diversity! Keep expanding",
    pendingPaymentInsight: "₹18,000 pending payment",
    pendingPaymentText: "Clear pending payments to build farmer trust",
    activeDealsInsight: "4 active deals in progress",
    activeDealsText: "Track delivery timelines for active deals",
    pendingPayments: "Pending Payments",
    dealsCompleted: "Deals Completed",
    purchaseOrders: "Purchase Orders",
    trackManageOrders: "Track and manage all your purchase orders",
    newOrder: "New Order",
    delivered: "Delivered",
    processing: "Processing",
    inTransit: "In Transit",
    searchOrders: "Search by order ID, supplier, or crop...",
    allOrders: "All Orders",
    filter: "Filter",
    orderDetails: "Order Details",
    supplier: "Supplier",
    amount: "Amount",
    status: "Status",
    actions: "Actions",
    paymentPaid: "Payment paid",
    paymentPending: "Payment pending",
    paymentPartial: "Payment partial",
    paymentRefunded: "Payment refunded",
    needHelp: "Need Help?",
    contactSupportText: "Contact support for order-related queries",
    contactSupport: "Contact Support",
    exportData: "Export Data",
    downloadReports: "Download order reports and invoices",
    exportOrders: "Export Orders",
    orderSummary: "Order Summary",
    avgOrder: "Avg Order",
    cropMarketplace: "Crop Marketplace",
    farmersBrowseCrops: "Farmers can browse real crops and send requests",
    cropsAvailable: "crops available",
    searchCropFarmerLocation: "Search crop, farmer, location...",
    allCrops: "All Crops",
    noCropsListed: "No farmers have listed crops yet",
    farmersLoginAddCrops: "Farmers can login and add crops from My Crops",
    marketplaceTips: "Marketplace Tips",
    requestSend: "Send Request",
    farmerAcceptDeal: "Once farmer accepts, deal will be created",
    negotiate: "Negotiate",
    negotiatePrice: "You can negotiate the price",
    trackRequest: "Track Request",
    trackOrders: "Track your requests from the Orders page",
    dealerDashboard: "Dealer Dashboard",
    welcomeDealerOverview: "Welcome back! Here's your business overview",
    monthlyRevenue: "Monthly Revenue",
    inventoryValue: "Inventory Value",
    orderId: "Order ID",
    topSuppliers: "Top Suppliers",
    viewAllSuppliers: "View All Suppliers",
    placeNewOrder: "Place New Order",
    findQualityCrops: "Find quality crops from farmers",
    browseMarketplace: "Browse Marketplace",
    trackInventory: "Track Inventory",
    manageStockLevels: "Manage your stock levels",
    viewInventory: "View Inventory",
    viewBusinessInsights: "View business insights",
    viewReports: "View Reports",
    openAgriAssist: "Open AgriAssist",
    export: "Export",
    activeSchemes: "Active Schemes",
    governmentSchemes: "Government Schemes List",
    browseAndApplyForSchemesDesignedForFarmers: "Browse and apply for schemes designed for farmers",
    live: "Live",
    schemesCount: "26 Schemes",
    searchSchemesByNameCropEligibility: "Search schemes by name, crop, eligibility...",
    allSchemes: "All Schemes",
    newScheme: "New Scheme",
    insurance: "Insurance",
    creditLoans: "Credit / Loans",
    irrigation: "Irrigation",
    cropSpecific: "Crop Specific",
    infrastructure: "Infrastructure",
    machinery: "Machinery",
    marketMSP: "Market / MSP",
    pension: "Pension",
    alliedSectors: "Allied Sectors",
    foodProcessing: "Food Processing",
    mspSupport: "MSP Support",
    soilTesting: "Soil Testing",
    dealsAndPayments: "Deals & Payments",
    manageYourDealsAndTrackAllTransactions: "Manage your deals and track all transactions",
    makePayment: "Make Payment",
    moneyReceived: "Money Received",
    activeDeals: "Active Deals",
    dealRevenue: "Deal Revenue",
    myDeals: "My Deals",
    payment: "Payment",
    noDealsFound: "No deals found",
    tryAdjustingYourFilters: "Try adjusting your filters",
    searchByCropOrDealer: "Search by crop or dealer",
    noRequestsFound: "No requests found",
    whenDealersShowInterestInYourCropsTheyWillAppearHere: "When dealers show interest in your crops, they will appear here",
    quickTips: "💡 Quick Tips",
    checkDealerRatings: "Check Dealer Ratings",
    alwaysVerifyDealerCredibilityBeforeAccepting: "Always verify dealer credibility before accepting",
    negotiateSmartly: "Negotiate Smartly",
    compareWithMarketPricesBeforeCountering: "Compare with market prices before countering",
    reviewDeliveryTerms: "Review Delivery Terms",
    ensureDeliveryDatesAndLogisticsAreClear: "Ensure delivery dates and logistics are clear",
    realTimeCropPricesAndMarketTrends: "Real-time crop prices and market trends",
    low: "Low",
    totalCropsTracked: "Total Crops Tracked",
    demand: "Demand",
    markets: "Markets",
    highestPrice: "Highest Price",
    avgPriceChange: "Avg Price Change",
    allRegions: "All Regions",
    allCategories: "All Categories",
    trending: "Trending",
    highDemand: "High Demand",
    cropDetails: "Crop Details",
    currentPrice: "Current Price",
    marketAndRegion: "Market & Region",
    trendPrediction: "Trend Prediction",
    veryHigh: "Very High",
    high: "High",
    medium: "Medium",
    stable: "Stable",
    bullish: "Bullish",
    growing: "Growing",
    rising: "Rising",
    seasonal: "Seasonal",
    declining: "Declining",
    addyourfirstcrop: "Add your first crop",
    tryadjustingyoursearchoraddanewcrop: "Try adjusting your search or add a new crop",
    nocropsfound: "No Crop Found",
    sold: "Sold",
    available: "Available",
    manageyourcropinventoryandlistings: "Manage your crop inventory and listings",
    searchcropsbynameorcategory: "Search crops by name or category...",
    totalCrop: "Total Crop",
    addNewCrops: "Add New Crops",
    norecentactivityyet: "No Recent Activity Yet",
    pendingRequests1: "Pending Requests",
    recentActivity: "Recent Activity",
    agriAssist: "AgriAssist",
    marketPrice: "Market Price",
    manageCrops: "Manage Crops",
    buyers: "Buyers",
    welcomeback: "Welcome back",

    // ── App General ──────────────────────────────────────────────────
    dashboard: "Dashboard",
    appName: "Agri Connect",
    login: "Login",
    register: "Register",
    logout: "Logout",
    getStarted: "Get Started",
    learnMore: "Learn More",
    whyChooseUs: "Why Choose Agri Connect?",
    directConnection: "Direct Connection",
    directConnectionDesc: "Connect farmers directly with dealers, eliminating middlemen",
    marketPricesDesc: "Real-time market prices and trends for informed decisions",
    community: "Community",
    communityDesc: "Join a thriving community of farmers and dealers",
    secure: "Secure Platform",
    secureDesc: "Safe and secure transactions with verified users",
    readyToStart: "Ready to Start Trading?",
    joinThousands: "Join thousands of farmers and dealers already on our platform",
    registerNow: "Register Now",
    allRightsReserved: "All rights reserved.",
    myCrops: "My Crops",
    marketplace: "Marketplace",
    orders: "Orders",
    suppliers: "Suppliers",
    schemes: "Government Schemes",
    advisor: "AI Advisor",
    requests: "Requests",
    users: "Users",
    analytics: "Analytics",
    profile: "Profile",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    name: "Full Name",
    loginAs: "Login as",
    registerAs: "Register as",
    dealer: "Dealer",
    government: "Government",
    admin: "Admin",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    backToHome: "Back to Home",
    welcomeBack: "Welcome back!",
    totalRevenue: "Total Revenue",
    inventory: "Inventory Items",
    welcomeDealer: "Welcome back! Here's your business overview.",
    farmers: "Farmers",
    dealers: "Dealers",
    districts: "Districts",
    helpTitle:        "Help & Guide",
    helpBtn:          "Help",
    helpContact:      "Need more help? Contact support@agriconnect.in",
    helpIntro:        "Introduction of Agri Connect",
    helpIntroDes:     "Know about our platform",
    helpLogin:        "Login Process",
    helpLoginDes:     "How to login to your account",
    helpRegister:     "Register Process",
    helpRegDes:       "Create new account",
    helpFarmer:       "Farmer Panel",
    helpFarmerDes:    "Guide for farmers",
    helpDealer:       "Dealer Panel",
    helpDealerDes:    "Guide for dealers",
    helpCustomer:     "Customer Panel",
    helpCustomerDes:  "Guide for customers",
    trade: "Traded",
  },

  hi: {
    // ── Home Page ────────────────────────────────────────────────────
    heroBadge:        "भारत का विश्वसनीय कृषि बाज़ार",
    heroTitle:        "स्वागत है",
    fairPrices:       "Agri Connect",
    heroSubtitle:     "किसानों, डीलरों और ग्राहकों के बीच सीधा व्यापार — कोई बिचौलिया नहीं, शोषण नहीं। बस उचित मूल्य और ताजा उत्पाद।",
    heroBtnFarmer:    "👨‍🌾 मैं किसान हूँ",
    heroBtnDealer:    "🏢 मैं डीलर हूँ",
    heroBtnCustomer:  "🛒 मैं ग्राहक हूँ",
    builtForYou:      "आपके लिए बना",
    whoFor:           "Agri Connect किसके लिए है?",
    whoForSub:        "चाहे आप उगाते हों, बेचते हों या खाते हों — Agri Connect आपके लिए बना है।",
    forFarmers:       "👨‍🌾 किसानों के लिए",
    forDealers:       "🏢 डीलरों के लिए",
    forCustomers:     "🛒 ग्राहकों के लिए",
    farmerHeadline:   "अपनी फसल सीधे बेचें। वो कमाएं जो आप deserve करते हैं।",
    farmerSub:        "कोई बिचौलिया नहीं। कोई शोषण नहीं। सीधे डीलरों और ग्राहकों से जुड़ें।",
    farmerBenefits:   ["✅ 2 मिनट में अपनी फसल लिस्ट करें","✅ सत्यापित डीलरों से सीधे अनुरोध पाएं","✅ कीमत negotiate करें — पूरा नियंत्रण आपके हाथ","✅ सुरक्षित भुगतान — सीधे आपके खाते में","✅ सभी बिक्री और कमाई एक डैशबोर्ड में","✅ सरकारी योजनाओं और फसल बीमा की जानकारी"],
    farmerCta:        "किसान के रूप में जुड़ें",
    farmerStat:       "किसान आय में औसत वृद्धि",
    dealerHeadline:   "सत्यापित किसानों से सीधे ताजा फसल प्राप्त करें।",
    dealerSub:        "मंडियों और बिचौलियों को छोड़ें। किसानों के साथ सीधे संबंध बनाएं।",
    dealerBenefits:   ["✅ 1000+ सत्यापित किसान ब्राउज़ करें","✅ फसल, स्थान, मूल्य के अनुसार फ़िल्टर करें","✅ सीधे request भेजें और negotiate करें","✅ रीयल-टाइम बाज़ार मूल्य देखें","✅ सभी supplier संबंध manage करें","✅ सुव्यवस्थित भुगतान और लेन-देन इतिहास"],
    dealerCta:        "डीलर के रूप में जुड़ें",
    dealerStat:       "खरीद लागत में कमी",
    customerHeadline: "खेत से सीधे ताजा उत्पाद, आपके दरवाजे तक।",
    customerSub:      "सीधे उस किसान से खरीदें जिसने उगाया। कोई कोल्ड स्टोरेज नहीं। बस शुद्ध ताजा उत्पाद।",
    customerBenefits: ["✅ पास के किसानों से सीधे ऑर्डर करें","✅ 100% ताजा — जल्दी काटा और deliver किया","✅ सुपरमार्केट से बेहतर दाम","✅ जानें आपका खाना किस खेत से आया","✅ हर खरीद से स्थानीय किसानों का समर्थन करें","✅ आसान ऑर्डरिंग"],
    customerCta:      "ताजा खरीदें",
    customerStat:     "बाज़ार मूल्य की तुलना में बचत",
    govSupport:       "सरकारी सहायता",
    govTitle:         "किसानों के लिए सरकारी योजनाएं",
    govSub:           "Agri Connect किसानों को उनकी हकदार सरकारी योजनाओं की जानकारी देता है।",
    checkEligibility: "पात्रता जांचें",
    schemeNote:       "Agri Connect आपकी profile के आधार पर सभी योजनाएं दिखाता है —",
    schemeFree:       "बिल्कुल मुफ्त।",
    discoverSchemes:  "अपनी योजनाएं खोजें",
    growingTitle:     "हर दिन बढ़ रहे हैं",
    growingSub:       "भारत भर के असली किसानों के असली आंकड़े",
    activeFarmers:    "सक्रिय किसान",
    verifiedDealers:  "सत्यापित डीलर",
    districtsLabel:   "जिले",
    totalTrade:       "कुल व्यापार",
    userStories:      " असली कहानियां",
    testimonialTitle: "हमारे उपयोगकर्ता क्या कहते हैं",
    startTrading:     "आज ही व्यापार शुरू करें",
    joinCommunity:    "10,000+ किसानों और 500+ डीलरों के साथ जुड़ें जो Agri Connect पर व्यापार कर रहे हैं।",
    registerFree:     "मुफ्त पंजीकरण करें",
    contactUs:        "संपर्क करें",
    freeReg:          "मुफ्त पंजीकरण",
    securePlatform:   "सुरक्षित प्लेटफॉर्म",
    easyToUse:        "उपयोग में आसान",
    farmerFirst:      "किसान पहले",
    platform:         "प्लेटफॉर्म",
    footerPlatformLinks: ["किसानों के लिए","डीलरों के लिए","ग्राहकों के लिए","सरकारी योजनाएं","बाज़ार भाव"],
    company:          "कंपनी",
    companyLinks:     ["हमारे बारे में","संपर्क","FAQ","गोपनीयता नीति","सेवा की शर्तें"],
    bridgeGap:        "किसानों और डीलरों के बीच की खाई को पाटना — एक टिकाऊ भविष्य के लिए।",
    incomeSupport:    "आय सहायता",
    cropInsurance:    "फसल बीमा",
    equipSubsidy:     "उपकरण सब्सिडी",
    marketAccess:     "बाज़ार पहुंच",
    organicFarming:   "जैविक खेती",
    farmerLoans:      "किसान ऋण",
    schemeDescs: [
      "पात्र किसान परिवारों को 3 समान किस्तों में ₹6,000/वर्ष की सीधी आय सहायता।",
      "कम प्रीमियम पर फसल बीमा — प्राकृतिक आपदाओं और कीटों से अपनी फसल बचाएं।",
      "छोटे और सीमांत किसानों के लिए कृषि मशीनरी पर 50-80% तक सब्सिडी।",
      "APMC मंडियों को जोड़ने वाला ऑनलाइन प्लेटफॉर्म — अपनी उपज के लिए बेहतर दाम पाएं।",
      "जैविक खेती को बढ़ावा देने के लिए 3 साल के लिए ₹50,000/हेक्टेयर।",
      "खेती की जरूरतों के लिए 4% ब्याज दर पर ₹3 लाख तक का आसान क्रेडिट।",
    ],

    // ── Customer Panel ───────────────────────────────────────────────
    welcome: "स्वागत है",
    freshProduce: "ताज़ा उत्पाद, सीधे किसानों से",
    totalOrders: "कुल ऑर्डर",
    pending: "लंबित",
    completed: "पूर्ण",
    totalSpent: "कुल खर्च",
    browseProducts: "उत्पाद देखें",
    myOrders: "मेरे ऑर्डर",
    transactions: "लेनदेन",
    myProfile: "मेरी प्रोफ़ाइल",
    freshCrops: "ताज़ी उपलब्ध फसलें",
    directFarmers: "आपके पास के किसानों से सीधे",
    viewAll: "सभी देखें",
    noCrops: "अभी कोई फसल उपलब्ध नहीं है",
    browseAllProducts: "सभी उत्पाद देखें",
    recentOrders: "हाल के ऑर्डर",
    latestRequests: "किसानों को आपके नवीनतम अनुरोध",
    noOrders: "अभी तक कोई ऑर्डर नहीं",
    browseNow: "अभी देखें",
    browseproductrequest: "उत्पाद देखें और किसानों को अनुरोध भेजें",
    browseFreshProducts: "ताज़े उत्पाद देखें",
    productsAvailable: "उत्पाद उपलब्ध — सीधे किसानों से",
    searchPlaceholder: "फसल, शहर, श्रेणी खोजें...",
    all: "सभी",
    latestFirst: "नवीनतम पहले",
    refresh: "रीफ्रेश",
    noProducts: "अभी कोई उत्पाद उपलब्ध नहीं है",
    farmersSoon: "किसान जल्द ही ताज़ी फसलें सूचीबद्ध करेंगे!",
    priceLowHigh: "कीमत: कम से अधिक",
    priceHighLow: "कीमत: अधिक से कम",
    mostQuantity: "अधिकतम मात्रा",
    negotiating: "बातचीत जारी",
    accepted: "स्वीकृत",
    rejected: "अस्वीकृत",
    cancelled: "रद्द",
    noOrdersFound: "कोई ऑर्डर नहीं मिला",
    noOrdersMessage: "आपने अभी तक कोई ऑर्डर नहीं किया है",
    myRequests: "मेरे अनुरोध",
    requestsToFarmers: "किसानों को अनुरोध",
    searchCropFarmer: "फसल या किसान खोजें...",
    noRequests: "अभी तक कोई अनुरोध नहीं",
    browseSendRequest: "उत्पाद देखें और किसानों को अनुरोध भेजें!",
    myTransactions: "मेरे लेनदेन",
    paymentHistory: "आपका पूरा भुगतान इतिहास",
    totalPaid: "कुल भुगतान",
    totalReceived: "कुल प्राप्त राशि",
    totalTransactions: "कुल लेनदेन",
    searchByIdUser: "आईडी या उपयोगकर्ता से खोजें...",
    failed: "असफल",
    noTransactionsFound: "कोई लेनदेन नहीं मिला",
    noPaymentHistory: "अभी तक कोई भुगतान इतिहास नहीं है",
    marketPrices: "मंडी कीमतें",
    liveApmmPrices: "पूरे भारत में लाइव APMC मंडी कीमतें",
    searchMarket: "फसल, किस्म या मंडी खोजें...",
    crop: "फसल",
    variety: "किस्म",
    grade: "ग्रेड",
    priceQuintal: "कीमत / क्विंटल",
    market: "मंडी",
    date: "तारीख",
    maharashtraPrices: "दिखाए गए भाव – महाराष्ट्र APMC मंडी",
    manageProfile: "अपनी प्रोफ़ाइल और प्राथमिकताएँ प्रबंधित करें",
    profileInfo: "प्रोफ़ाइल जानकारी",
    notifications: "सूचनाएँ",
    fullName: "पूरा नाम",
    emailAddress: "ईमेल पता",
    city: "शहर",
    state: "राज्य",
    phone: "फोन",
    address: "पता",
    username: "उपयोगकर्ता नाम",
    role: "भूमिका",
    editProfile: "प्रोफ़ाइल संपादित करें",
    accountSecurity: "खाता सुरक्षा",
    accountStatus: "खाता स्थिति",
    verified: "सत्यापित",
    changePassword: "पासवर्ड बदलें",
    memberSince: "सदस्यता शुरू",
    active: "सक्रिय",
    quickActions: "त्वरित कार्य",
    deleteAccount: "खाता हटाएं",
    dangerZone: "खतरे का क्षेत्र",
    deleteAccountMessage: "अपने खाते और सभी डेटा को स्थायी रूप से हटाएं",
    accountVerified: "आपका खाता सत्यापित है",
    updatePasswordMsg: "आप कभी भी अपना लॉगिन पासवर्ड अपडेट कर सकते हैं",
    deleteAccountMsg: "अपने खाते और सभी डेटा को स्थायी रूप से हटाएं",
    spent: "खर्च",
    joined: "शामिल हुआ",
    notificationPreferences: "सूचना प्राथमिकताएँ",
    orderUpdates: "ऑर्डर अपडेट्स",
    orderUpdatesDesc: "जब ऑर्डर की स्थिति बदलती है",
    requestResponses: "अनुरोध प्रतिक्रियाएँ",
    requestResponsesDesc: "जब किसान आपके अनुरोधों का जवाब देते हैं",
    paymentAlerts: "भुगतान अलर्ट",
    paymentAlertsDesc: "जब भुगतान प्रक्रिया पूरी होती है",
    marketPriceUpdates: "बाजार मूल्य अपडेट",
    marketPriceUpdatesDesc: "फसल की कीमतों के दैनिक अपडेट",
    newProducts: "नए उत्पाद",
    newProductsDesc: "जब किसान नए उत्पाद जोड़ते हैं",
    saveSettings: "सेटिंग्स सहेजें",
    change: "बदलें",
    delete: "हटाएं",
    sendRequestsToFarmers: "किसानों को अनुरोध भेजें",
    totalApplicants: "कुल आवेदक",
    totalBudget: "कुल बजट",
    applicants: "आवेदक",
    approved: "स्वीकृत",
    applicationProgress: "आवेदन प्रगति",
    deadline: "अंतिम तिथि",
    budget: "बजट",
    coverage: "कवरेज",
    launched: "लॉन्च",
    keyFeatures: "मुख्य विशेषताएँ",
    viewDetails: "विवरण देखें",
    adjustSearchFilter: "आपकी खोज या फ़िल्टर बदलकर देखें।",
    createNewScheme: "नई योजना बनाएं",
    accountVerifiedMessage: "आपका खाता सत्यापित है",
    updatePasswordText: "कभी भी अपना लॉगिन पासवर्ड अपडेट करें",
    deleteAccountText: "अपने खाते और सभी डेटा को स्थायी रूप से हटाएं",
    manageFarmerAccount: "अपने किसान खाते और सेटिंग्स प्रबंधित करें",
    security: "सुरक्षा",
    profileInformation: "प्रोफ़ाइल जानकारी",
    farmSize: "खेत का आकार",
    farmingExperience: "खेती का अनुभव",
    farmAddress: "खेत का पता",
    verifiedAccount: "सत्यापित खाता",
    crops: "फसलें",
    deals: "सौदे",
    revenue: "राजस्व",
    notificationSettings: "सूचना सेटिंग्स",
    farmer: "किसान",
    payments: "भुगतान",
    managePayments: "किसानों को किए गए भुगतान प्रबंधित करें",
    total: "कुल",
    exportCSV: "CSV निर्यात",
    payFarmer: "किसान को भुगतान करें",
    noPaymentsYet: "अभी तक कोई भुगतान नहीं",
    clickPayFarmer: 'पहला भुगतान करने के लिए "किसान को भुगतान करें" पर क्लिक करें',
    businessProfile: "व्यवसाय प्रोफ़ाइल",
    manageDealershipProfile: "अपने डीलरशिप प्रोफ़ाइल और व्यवसाय जानकारी प्रबंधित करें",
    businessInformation: "व्यवसाय जानकारी",
    businessName: "व्यवसाय का नाम",
    ownerName: "मालिक का नाम",
    contactNumber: "संपर्क नंबर",
    businessType: "व्यवसाय प्रकार",
    gstNumber: "जीएसटी नंबर",
    establishmentYear: "स्थापना वर्ष",
    established: "स्थापित",
    licenseNumber: "लाइसेंस नंबर",
    license: "लाइसेंस",
    businessAddress: "व्यवसाय पता",
    specialization: "विशेषज्ञता",
    businessSettings: "व्यवसाय सेटिंग्स",
    paymentMethods: "भुगतान विधियाँ",
    manageAcceptedPayments: "स्वीकृत भुगतान विधियों को प्रबंधित करें",
    deliverySettings: "डिलीवरी सेटिंग्स",
    configureDeliveryLogistics: "डिलीवरी और लॉजिस्टिक्स कॉन्फ़िगर करें",
    configure: "कॉन्फ़िगर",
    setup: "सेटअप",
    tradeAreas: "व्यापार क्षेत्र",
    activeSuppliers: "सक्रिय सप्लायर",
    monthlyOrders: "मासिक ऑर्डर",
    satisfaction: "संतुष्टि",
    premiumPartner: "प्रीमियम पार्टनर",
    saveProfile: "प्रोफ़ाइल सेव करें",
    wholesaleDistributor: "थोक वितरक",
    grains: "अनाज",
    vegetables: "सब्जियाँ",
    cashCrops: "नकदी फसलें",
    mySuppliers: "मेरे सप्लायर",
    manageSuppliers: "जिन किसानों से आपने डील या रिक्वेस्ट की है",
    addNewSupplier: "नया सप्लायर जोड़ें",
    totalSuppliers: "कुल सप्लायर",
    totalValue: "कुल मूल्य",
    searchSuppliers: "नाम या स्थान से सप्लायर खोजें...",
    allStatus: "सभी स्थिति",
    inactive: "निष्क्रिय",
    mainCrops: "मुख्य फसलें",
    reliability: "विश्वसनीयता",
    contact: "संपर्क करें",
    orderNow: "ऑर्डर करें",
    noSuppliersYet: "अभी कोई सप्लायर नहीं",
    noMatchingSuppliers: "कोई मिलते सप्लायर नहीं",
    clearSearch: "खोज साफ़ करें",
    goToMarketplace: "मार्केटप्लेस पर जाएं",
    businessAnalytics: "व्यापार विश्लेषण",
    realTimeInsights: "आपके डीलरशिप प्रदर्शन की रीयल-टाइम जानकारी",
    lastMonth: "पिछला महीना",
    totalSpentLabel: "कुल खर्च",
    completedDeals: "पूर्ण डील",
    farmersSourced: "किसान स्रोत",
    totalRequests: "कुल अनुरोध",
    monthlySpending: "मासिक खर्च",
    last6Months: "पिछले 6 महीने",
    topCropsPurchased: "सबसे अधिक खरीदी गई फसलें",
    requestStatus: "अनुरोध स्थिति",
    businessInsights: "व्यापार अंतर्दृष्टि",
    topPurchaseInsight: "गेहूं आपकी सबसे अधिक खरीद है",
    topPurchaseText: "₹1,25,000 गेहूं पर खर्च",
    farmersInsight: "12 अलग-अलग किसान स्रोत",
    farmersInsightText: "अच्छी सप्लायर विविधता! इसे बढ़ाते रहें",
    pendingPaymentInsight: "₹18,000 भुगतान लंबित",
    pendingPaymentText: "किसानों का विश्वास बनाने के लिए भुगतान करें",
    activeDealsInsight: "4 सक्रिय डील चल रही हैं",
    activeDealsText: "सक्रिय डील की डिलीवरी ट्रैक करें",
    pendingPayments: "लंबित भुगतान",
    dealsCompleted: "पूर्ण डील",
    purchaseOrders: "खरीद ऑर्डर",
    trackManageOrders: "अपने सभी खरीद ऑर्डर ट्रैक और प्रबंधित करें",
    newOrder: "नया ऑर्डर",
    delivered: "डिलीवर",
    processing: "प्रोसेसिंग",
    inTransit: "ट्रांज़िट में",
    searchOrders: "ऑर्डर आईडी, सप्लायर या फसल से खोजें...",
    allOrders: "सभी ऑर्डर",
    filter: "फ़िल्टर",
    orderDetails: "ऑर्डर विवरण",
    supplier: "सप्लायर",
    amount: "राशि",
    status: "स्थिति",
    actions: "कार्य",
    paymentPaid: "भुगतान किया गया",
    paymentPending: "भुगतान लंबित",
    paymentPartial: "आंशिक भुगतान",
    paymentRefunded: "भुगतान वापस",
    needHelp: "मदद चाहिए?",
    contactSupportText: "ऑर्डर से संबंधित प्रश्नों के लिए सहायता से संपर्क करें",
    contactSupport: "संपर्क करें",
    exportData: "डेटा निर्यात",
    downloadReports: "ऑर्डर रिपोर्ट और इनवॉइस डाउनलोड करें",
    exportOrders: "ऑर्डर निर्यात करें",
    orderSummary: "ऑर्डर सारांश",
    avgOrder: "औसत ऑर्डर",
    cropMarketplace: "फसल बाज़ार",
    farmersBrowseCrops: "किसान असली फसलें ब्राउज़ कर सकते हैं और अनुरोध भेज सकते हैं",
    cropsAvailable: "फसलें उपलब्ध",
    searchCropFarmerLocation: "फसल, किसान, स्थान खोजें...",
    allCrops: "सभी फसलें",
    noCropsListed: "अभी तक किसी किसान ने फसल सूचीबद्ध नहीं की है",
    farmersLoginAddCrops: "किसान लॉगिन करके My Crops से फसल जोड़ सकते हैं",
    marketplaceTips: "मार्केटप्लेस सुझाव",
    requestSend: "अनुरोध भेजें",
    farmerAcceptDeal: "किसान के स्वीकार करने पर डील बनेगी",
    negotiate: "मोलभाव करें",
    negotiatePrice: "आप कीमत पर बातचीत कर सकते हैं",
    trackRequest: "अनुरोध ट्रैक करें",
    trackOrders: "Orders पेज से अनुरोध ट्रैक करें",
    dealerDashboard: "डीलर डैशबोर्ड",
    welcomeDealerOverview: "वापसी पर स्वागत है! यहाँ आपके व्यवसाय का अवलोकन है",
    monthlyRevenue: "मासिक राजस्व",
    inventoryValue: "इन्वेंटरी मूल्य",
    orderId: "ऑर्डर आईडी",
    topSuppliers: "शीर्ष आपूर्तिकर्ता",
    viewAllSuppliers: "सभी आपूर्तिकर्ता देखें",
    placeNewOrder: "नया ऑर्डर करें",
    findQualityCrops: "किसानों से अच्छी फसलें खोजें",
    browseMarketplace: "मार्केटप्लेस देखें",
    trackInventory: "इन्वेंटरी ट्रैक करें",
    manageStockLevels: "अपने स्टॉक स्तर प्रबंधित करें",
    viewInventory: "इन्वेंटरी देखें",
    viewBusinessInsights: "व्यापार विश्लेषण देखें",
    viewReports: "रिपोर्ट देखें",
    openAgriAssist: "एग्रीअसिस्ट खोलें",
    export: "निर्यात",
    activeSchemes: "सक्रिय योजनाएँ",
    governmentSchemes: "सरकारी योजनाएं",
    browseAndApplyForSchemesDesignedForFarmers: "किसानों के लिए बनाई गई योजनाओं को देखें और आवेदन करें",
    live: "लाइव",
    schemesCount: "26 योजनाएं",
    searchSchemesByNameCropEligibility: "नाम, फसल या पात्रता के अनुसार योजनाएं खोजें...",
    allSchemes: "सभी योजनाएं",
    newScheme: "नई योजना",
    insurance: "बीमा",
    creditLoans: "क्रेडिट / ऋण",
    irrigation: "सिंचाई",
    cropSpecific: "विशिष्ट फसल",
    infrastructure: "बुनियादी ढांचा",
    machinery: "मशीनरी",
    marketMSP: "बाजार / एमएसपी",
    pension: "पेंशन",
    alliedSectors: "संबद्ध क्षेत्र",
    foodProcessing: "खाद्य प्रसंस्करण",
    mspSupport: "एमएसपी सहायता",
    soilTesting: "मिट्टी परीक्षण",
    dealsAndPayments: "डील्स और भुगतान",
    manageYourDealsAndTrackAllTransactions: "अपनी डील्स प्रबंधित करें और सभी लेनदेन ट्रैक करें",
    makePayment: "भुगतान करें",
    moneyReceived: "प्राप्त धन",
    activeDeals: "सक्रिय डील्स",
    dealRevenue: "डील राजस्व",
    myDeals: "मेरी डील्स",
    payment: "भुगतान",
    noDealsFound: "कोई डील नहीं मिली",
    tryAdjustingYourFilters: "अपने फ़िल्टर समायोजित करने का प्रयास करें",
    searchByCropOrDealer: "फसल या व्यापारी के अनुसार खोजें",
    noRequestsFound: "कोई अनुरोध नहीं मिला",
    whenDealersShowInterestInYourCropsTheyWillAppearHere: "जब व्यापारी आपकी फसलों में रुचि दिखाएंगे तो वे यहाँ दिखाई देंगे",
    quickTips: "💡 त्वरित सुझाव",
    checkDealerRatings: "व्यापारी की रेटिंग जांचें",
    alwaysVerifyDealerCredibilityBeforeAccepting: "स्वीकार करने से पहले व्यापारी की विश्वसनीयता अवश्य जांचें",
    negotiateSmartly: "समझदारी से बातचीत करें",
    compareWithMarketPricesBeforeCountering: "काउंटर करने से पहले बाजार मूल्य से तुलना करें",
    reviewDeliveryTerms: "डिलीवरी की शर्तों की समीक्षा करें",
    ensureDeliveryDatesAndLogisticsAreClear: "सुनिश्चित करें कि डिलीवरी तिथि और लॉजिस्टिक्स स्पष्ट हों",
    realTimeCropPricesAndMarketTrends: "रीयल-टाइम फसल कीमतें और बाजार रुझान",
    low: "कम",
    totalCropsTracked: "कुल ट्रैक की गई फसलें",
    demand: "मांग",
    markets: "बाजार",
    highestPrice: "सबसे अधिक कीमत",
    avgPriceChange: "औसत कीमत परिवर्तन",
    allRegions: "सभी क्षेत्र",
    allCategories: "सभी श्रेणियां",
    trending: "ट्रेंडिंग",
    highDemand: "उच्च मांग",
    cropDetails: "फसल विवरण",
    currentPrice: "वर्तमान कीमत",
    marketAndRegion: "बाजार और क्षेत्र",
    trendPrediction: "रुझान पूर्वानुमान",
    veryHigh: "बहुत अधिक",
    high: "अधिक",
    medium: "मध्यम",
    stable: "स्थिर",
    bullish: "तेजी का संकेत",
    growing: "बढ़ रहा है",
    rising: "ऊपर जा रहा है",
    seasonal: "मौसमी",
    declining: "घट रहा है",
    addyourfirstcrop: "अपनी पहली फसल जोड़ें",
    tryadjustingyoursearchoraddanewcrop: "अपनी खोज को समायोजित करने का प्रयास करें या नया क्रॉप जोड़ें",
    nocropsfound: "कोई फसल नहीं मिली",
    sold: "बिका",
    available: "उपलब्ध",
    manageyourcropinventoryandlistings: "अपनी फसल की सूची और इन्वेंट्री का प्रबंधन करें।",
    searchcropsbynameorcategory: "फसलों को नाम या श्रेणी के आधार पर खोजें...",
    totalCrop: "कुल फसल",
    addNewCrops: "नई फसलें जोड़ें",
    norecentactivityyet: "अभी तक कोई हालिया गतिविधि नहीं",
    pendingRequests1: "लंबित अनुरोध",
    recentActivity: "हाल की गतिविधि",
    agriAssist: "कृषि सहायता",
    marketPrice: "बाजार कीमत",
    manageCrops: "फसलों का प्रबंधन करें",
    buyers: "खरीदार",
    welcomeback: "वापसी पर स्वागत है",

    // ── App General ──────────────────────────────────────────────────
    dashboard: "डैशबोर्ड",
    appName: "एग्री कनेक्ट",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    getStarted: "शुरू करें",
    learnMore: "अधिक जानें",
    whyChooseUs: "एग्री कनेक्ट क्यों चुनें?",
    directConnection: "सीधा संपर्क",
    directConnectionDesc: "बिचौलियों को हटाकर किसानों को डीलरों से सीधे जोड़ें",
    marketPricesDesc: "सूचित निर्णयों के लिए वास्तविक समय बाजार मूल्य और रुझान",
    community: "समुदाय",
    communityDesc: "किसानों और डीलरों के एक संपन्न समुदाय में शामिल हों",
    secure: "सुरक्षित मंच",
    secureDesc: "सत्यापित उपयोगकर्ताओं के साथ सुरक्षित लेनदेन",
    readyToStart: "व्यापार शुरू करने के लिए तैयार हैं?",
    joinThousands: "हमारे प्लेटफॉर्म पर पहले से मौजूद हजारों किसानों और डीलरों से जुड़ें",
    registerNow: "अभी पंजीकरण करें",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    myCrops: "मेरी फसलें",
    marketplace: "बाज़ार",
    orders: "आदेश",
    suppliers: "आपूर्तिकर्ता",
    schemes: "सरकारी योजनाएं",
    advisor: "एआई सलाहकार",
    requests: "अनुरोध",
    users: "उपयोगकर्ता",
    analytics: "विश्लेषण",
    profile: "प्रोफ़ाइल",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    name: "पूरा नाम",
    loginAs: "के रूप में लॉगिन करें",
    registerAs: "के रूप में पंजीकरण करें",
    dealer: "व्यापारी",
    government: "सरकार",
    admin: "व्यवस्थापक",
    dontHaveAccount: "खाता नहीं है?",
    alreadyHaveAccount: "पहले से खाता है?",
    backToHome: "होम पर वापस जाएं",
    welcomeBack: "वापसी पर स्वागत है!",
    totalRevenue: "कुल राजस्व",
    inventory: "इन्वेंटरी आइटम",
    welcomeDealer: "वापसी पर स्वागत है! यहाँ आपके व्यवसाय का अवलोकन है।",
    farmers: "किसान",
    dealers: "डीलर",
    districts: "जिले",
    helpTitle:        "सहायता और मार्गदर्शिका",
    helpBtn:          "सहायता",
    helpContact:      "अधिक सहायता? संपर्क करें support@agriconnect.in",
    helpIntro:        "Agri Connect का परिचय",
    helpIntroDes:     "हमारे प्लेटफॉर्म के बारे में जानें",
    helpLogin:        "लॉगिन प्रक्रिया",
    helpLoginDes:     "अपने खाते में लॉगिन कैसे करें",
    helpRegister:     "पंजीकरण प्रक्रिया",
    helpRegDes:       "नया खाता बनाएं",
    helpFarmer:       "किसान पैनल",
    helpFarmerDes:    "किसानों के लिए मार्गदर्शिका",
    helpDealer:       "डीलर पैनल",
    helpDealerDes:    "डीलरों के लिए मार्गदर्शिका",
    helpCustomer:     "ग्राहक पैनल",
    helpCustomerDes:  "ग्राहकों के लिए मार्गदर्शिका",
    trade: "व्यापार",
  },

  mr: {
    // ── Home Page ────────────────────────────────────────────────────
    heroBadge:        "भारतातील विश्वासार्ह कृषी बाजारपेठ",
    heroTitle:        "स्वागत आहे",
    fairPrices:       "Agri Connect",
    heroSubtitle:     "शेतकरी, व्यापारी आणि ग्राहक यांच्यात थेट व्यापार — कोणता मध्यस्थ नाही. फक्त योग्य भाव आणि ताजी उत्पादने।",
    heroBtnFarmer:    "👨‍🌾 मी शेतकरी आहे",
    heroBtnDealer:    "🏢 मी व्यापारी आहे",
    heroBtnCustomer:  "🛒 मी ग्राहक आहे",
    builtForYou:      "तुमच्यासाठी बनवले",
    whoFor:           "Agri Connect कोणासाठी आहे?",
    whoForSub:        "तुम्ही पिकवा, विका किंवा खा — Agri Connect तुमच्यासाठी आहे।",
    forFarmers:       "👨‍🌾 शेतकऱ्यांसाठी",
    forDealers:       "🏢 व्यापाऱ्यांसाठी",
    forCustomers:     "🛒 ग्राहकांसाठी",
    farmerHeadline:   "तुमचे पीक थेट विका. तुम्हाला पात्र ते मिळवा।",
    farmerSub:        "कोणता मध्यस्थ नाही. शोषण नाही. थेट व्यापारी आणि ग्राहकांशी संपर्क साधा।",
    farmerBenefits:   ["✅ 2 मिनिटांत पीक नोंदवा","✅ सत्यापित व्यापाऱ्यांकडून थेट विनंत्या","✅ किंमत negotiate करा — संपूर्ण नियंत्रण तुमच्या हाती","✅ सुरक्षित पेमेंट — थेट तुमच्या खात्यात","✅ सर्व विक्री एका डॅशबोर्डवर","✅ सरकारी योजना माहिती"],
    farmerCta:        "शेतकरी म्हणून सामील व्हा",
    farmerStat:       "शेतकरी उत्पन्नात सरासरी वाढ",
    dealerHeadline:   "सत्यापित शेतकऱ्यांकडून थेट ताजी पिके मिळवा।",
    dealerSub:        "मंडई आणि मध्यस्थ सोडा. शेतकऱ्यांशी थेट संबंध निर्माण करा.",
    dealerBenefits:   ["✅ 1000+ सत्यापित शेतकरी पाहा","✅ पीक, स्थान, किंमतीनुसार फिल्टर करा","✅ थेट request पाठवा","✅ रिअल-टाइम बाजार भाव पाहा","✅ सर्व पुरवठादार manage करा","✅ सुव्यवस्थित पेमेंट इतिहास"],
    dealerCta:        "व्यापारी म्हणून सामील व्हा",
    dealerStat:       "खरेदी खर्चात कपात",
    customerHeadline: "शेतातून थेट ताजे उत्पादन, तुमच्या दारापर्यंत।",
    customerSub:      "थेट शेतकऱ्याकडून खरेदी करा. कोल्ड स्टोरेज नाही. शुद्ध ताजे उत्पादन।",
    customerBenefits: ["✅ जवळच्या शेतकऱ्यांकडून थेट ऑर्डर करा","✅ 100% ताजे — लवकर deliver","✅ सुपरमार्केटपेक्षा चांगले भाव","✅ अन्न कोणत्या शेतातून आले ते जाणा","✅ स्थानिक शेतकऱ्यांना समर्थन द्या","✅ सोपी ऑर्डरिंग"],
    customerCta:      "ताजे खरेदी करा",
    customerStat:     "बाजारभावापेक्षा बचत",
    govSupport:       "सरकारी सहाय्य",
    govTitle:         "शेतकऱ्यांसाठी सरकारी योजना",
    govSub:           "Agri Connect शेतकऱ्यांना त्यांच्या हक्काच्या सरकारी योजनांची माहिती देते।",
    checkEligibility: "पात्रता तपासा",
    schemeNote:       "Agri Connect तुमच्या profile नुसार सर्व योजना दाखवते —",
    schemeFree:       "पूर्णपणे मोफत।",
    discoverSchemes:  "तुमच्या योजना शोधा",
    growingTitle:     "दररोज वाढत आहे",
    growingSub:       "संपूर्ण भारतातील खऱ्या शेतकऱ्यांचे खरे आकडे",
    activeFarmers:    "सक्रिय शेतकरी",
    verifiedDealers:  "सत्यापित व्यापारी",
    districtsLabel:   "जिल्हे",
    totalTrade:       "एकूण व्यापार",
    userStories:      " खऱ्या कहाण्या",
    testimonialTitle: "आमचे वापरकर्ते काय म्हणतात",
    startTrading:     "आजच व्यापार सुरू करा",
    joinCommunity:    "Agri Connect वर आधीच व्यवसाय करणाऱ्या 10,000+ शेतकरी आणि 500+ व्यापाऱ्यांसोबत सामील व्हा।",
    registerFree:     "मोफत नोंदणी करा",
    contactUs:        "संपर्क करा",
    freeReg:          "मोफत नोंदणी",
    securePlatform:   "सुरक्षित प्लॅटफॉर्म",
    easyToUse:        "वापरायला सोपे",
    farmerFirst:      "शेतकरी प्रथम",
    platform:         "प्लॅटफॉर्म",
    footerPlatformLinks: ["शेतकऱ्यांसाठी","व्यापाऱ्यांसाठी","ग्राहकांसाठी","सरकारी योजना","बाजार भाव"],
    company:          "कंपनी",
    companyLinks:     ["आमच्याबद्दल","संपर्क","FAQ","गोपनीयता धोरण","सेवेच्या अटी"],
    bridgeGap:        "शेतकरी आणि व्यापारी यांच्यातील अंतर कमी करणे — शाश्वत भविष्यासाठी।",
    incomeSupport:    "उत्पन्न सहाय्य",
    cropInsurance:    "पीक विमा",
    equipSubsidy:     "उपकरण अनुदान",
    marketAccess:     "बाजार प्रवेश",
    organicFarming:   "सेंद्रिय शेती",
    farmerLoans:      "शेतकरी कर्ज",
    schemeDescs: [
      "पात्र शेतकरी कुटुंबांना 3 समान हप्त्यांमध्ये ₹6,000/वर्ष थेट उत्पन्न सहाय्य।",
      "कमी प्रीमियमवर पीक विमा — नैसर्गिक आपत्ती आणि कीडांपासून पिकांचे रक्षण करा।",
      "लहान व सीमांत शेतकऱ्यांसाठी शेती यंत्रांवर 50-80% अनुदान।",
      "APMC बाजारांना जोडणारे ऑनलाइन व्यासपीठ — उत्पादनाला चांगला भाव मिळवा।",
      "सेंद्रिय शेतीला प्रोत्साहन देण्यासाठी 3 वर्षांसाठी ₹50,000/हेक्टेयर।",
      "शेतीच्या गरजांसाठी 4% व्याजदराने ₹3 लाखांपर्यंत सहज कर्ज।",
    ],

    // ── Customer Panel ───────────────────────────────────────────────
    welcome: "स्वागत आहे",
    freshProduce: "ताजे उत्पादन, थेट शेतकऱ्यांकडून",
    totalOrders: "एकूण ऑर्डर",
    pending: "प्रलंबित",
    completed: "पूर्ण",
    totalSpent: "एकूण खर्च",
    browseProducts: "उत्पादने पाहा",
    myOrders: "माझे ऑर्डर",
    transactions: "व्यवहार",
    myProfile: "माझी प्रोफाइल",
    freshCrops: "ताजी उपलब्ध पिके",
    directFarmers: "तुमच्या जवळच्या शेतकऱ्यांकडून थेट",
    viewAll: "सर्व पाहा",
    noCrops: "सध्या कोणतीही पिके उपलब्ध नाहीत",
    browseAllProducts: "सर्व उत्पादने पाहा",
    recentOrders: "अलीकडील ऑर्डर",
    latestRequests: "शेतकऱ्यांना तुमच्या अलीकडील विनंत्या",
    noOrders: "अजून ऑर्डर नाहीत",
    browseNow: "आता पाहा",
    browseproductrequest: "उत्पादने पाहा आणि शेतकऱ्यांना विनंती पाठवा",
    browseFreshProducts: "ताजी उत्पादने पाहा",
    productsAvailable: "उत्पादने उपलब्ध — थेट शेतकऱ्यांकडून",
    searchPlaceholder: "पीक, शहर, श्रेणी शोधा...",
    all: "सर्व",
    latestFirst: "नवीनतम प्रथम",
    refresh: "रिफ्रेश",
    noProducts: "सध्या कोणतीही उत्पादने उपलब्ध नाहीत",
    farmersSoon: "शेतकरी लवकरच ताजी पिके सूचीबद्ध करतील!",
    priceLowHigh: "किंमत: कमी ते जास्त",
    priceHighLow: "किंमत: जास्त ते कमी",
    mostQuantity: "सर्वाधिक प्रमाण",
    negotiating: "वाटाघाटी सुरू",
    accepted: "स्वीकारले",
    rejected: "नाकारले",
    cancelled: "रद्द",
    noOrdersFound: "कोणतेही ऑर्डर सापडले नाहीत",
    noOrdersMessage: "तुम्ही अजून कोणतेही ऑर्डर केलेले नाहीत",
    myRequests: "माझ्या विनंत्या",
    requestsToFarmers: "शेतकऱ्यांना विनंत्या",
    searchCropFarmer: "पीक किंवा शेतकरी शोधा...",
    noRequests: "अजून कोणतीही विनंती नाही",
    browseSendRequest: "उत्पादने पाहा आणि शेतकऱ्यांना विनंती पाठवा!",
    myTransactions: "माझे व्यवहार",
    paymentHistory: "तुमचा संपूर्ण पेमेंट इतिहास",
    totalPaid: "एकूण भरलेली रक्कम",
    totalReceived: "एकूण प्राप्त रक्कम",
    totalTransactions: "एकूण व्यवहार",
    searchByIdUser: "आयडी किंवा वापरकर्त्याने शोधा...",
    failed: "अयशस्वी",
    noTransactionsFound: "कोणतेही व्यवहार सापडले नाहीत",
    noPaymentHistory: "अजून कोणताही पेमेंट इतिहास नाही",
    marketPrices: "बाजार भाव",
    liveApmmPrices: "संपूर्ण भारतातील थेट APMC बाजार भाव",
    searchMarket: "पीक, प्रकार किंवा बाजार शोधा...",
    crop: "पीक",
    variety: "प्रकार",
    grade: "दर्जा",
    priceQuintal: "किंमत / क्विंटल",
    market: "बाजार",
    date: "तारीख",
    maharashtraPrices: "दाखवलेले भाव – महाराष्ट्र APMC बाजार",
    manageProfile: "तुमची प्रोफाइल आणि सेटिंग्ज व्यवस्थापित करा",
    profileInfo: "प्रोफाइल माहिती",
    notifications: "सूचना",
    fullName: "पूर्ण नाव",
    emailAddress: "ईमेल पत्ता",
    city: "शहर",
    state: "राज्य",
    phone: "फोन",
    address: "पत्ता",
    username: "वापरकर्तानाव",
    role: "भूमिका",
    editProfile: "प्रोफाइल संपादित करा",
    accountSecurity: "खाते सुरक्षा",
    accountStatus: "खाते स्थिती",
    verified: "सत्यापित",
    changePassword: "पासवर्ड बदला",
    memberSince: "सदस्यत्व सुरू",
    active: "सक्रिय",
    quickActions: "जलद क्रिया",
    deleteAccount: "खाते हटवा",
    dangerZone: "धोक्याचा विभाग",
    deleteAccountMessage: "तुमचे खाते आणि सर्व डेटा कायमस्वरूपी हटवा",
    accountVerified: "तुमचे खाते सत्यापित आहे",
    updatePasswordMsg: "तुम्ही कधीही तुमचा लॉगिन पासवर्ड अपडेट करू शकता",
    deleteAccountMsg: "तुमचे खाते आणि सर्व डेटा कायमस्वरूपी हटवा",
    spent: "खर्च",
    joined: "नोंदणी केली",
    notificationPreferences: "सूचना प्राधान्ये",
    orderUpdates: "ऑर्डर अपडेट्स",
    orderUpdatesDesc: "ऑर्डर स्थिती बदलल्यावर",
    requestResponses: "विनंती प्रतिसाद",
    requestResponsesDesc: "शेतकरी तुमच्या विनंत्यांना प्रतिसाद देतात तेव्हा",
    paymentAlerts: "पेमेंट सूचना",
    paymentAlertsDesc: "पेमेंट प्रक्रिया झाल्यावर",
    marketPriceUpdates: "बाजार भाव अपडेट्स",
    marketPriceUpdatesDesc: "पीकांच्या किंमतींचे दररोज अपडेट",
    newProducts: "नवीन उत्पादने",
    newProductsDesc: "शेतकरी नवीन उत्पादने जोडतात तेव्हा",
    saveSettings: "सेटिंग्ज जतन करा",
    change: "बदला",
    delete: "हटवा",
    sendRequestsToFarmers: "शेतकऱ्यांना विनंत्या पाठवा",
    totalApplicants: "एकूण अर्जदार",
    totalBudget: "एकूण बजेट",
    applicants: "अर्जदार",
    approved: "मंजूर",
    applicationProgress: "अर्ज प्रगती",
    deadline: "अंतिम तारीख",
    budget: "बजेट",
    coverage: "कव्हरेज",
    launched: "लाँच",
    keyFeatures: "मुख्य वैशिष्ट्ये",
    viewDetails: "तपशील पहा",
    adjustSearchFilter: "तुमचा शोध किंवा फिल्टर बदलून पाहा.",
    createNewScheme: "नवीन योजना तयार करा",
    accountVerifiedMessage: "तुमचे खाते सत्यापित आहे",
    updatePasswordText: "कधीही तुमचा लॉगिन पासवर्ड अपडेट करा",
    deleteAccountText: "तुमचे खाते आणि सर्व डेटा कायमस्वरूपी हटवा",
    manageFarmerAccount: "तुमचे शेतकरी खाते आणि सेटिंग्ज व्यवस्थापित करा",
    security: "सुरक्षा",
    profileInformation: "प्रोफाइल माहिती",
    farmSize: "शेतीचे क्षेत्र",
    farmingExperience: "शेतीचा अनुभव",
    farmAddress: "शेतीचा पत्ता",
    verifiedAccount: "सत्यापित खाते",
    crops: "पिके",
    deals: "सौदे",
    revenue: "उत्पन्न",
    notificationSettings: "सूचना सेटिंग्ज",
    farmer: "शेतकरी",
    payments: "पेमेंट्स",
    managePayments: "शेतकऱ्यांना केलेले पेमेंट व्यवस्थापित करा",
    total: "एकूण",
    exportCSV: "CSV निर्यात",
    payFarmer: "शेतकऱ्याला पेमेंट करा",
    noPaymentsYet: "अजून कोणतेही पेमेंट नाही",
    clickPayFarmer: 'पहिले पेमेंट करण्यासाठी "शेतकऱ्याला पेमेंट करा" क्लिक करा',
    businessProfile: "व्यवसाय प्रोफाइल",
    manageDealershipProfile: "तुमची डीलरशिप प्रोफाइल आणि व्यवसाय माहिती व्यवस्थापित करा",
    businessInformation: "व्यवसाय माहिती",
    businessName: "व्यवसाय नाव",
    ownerName: "मालकाचे नाव",
    contactNumber: "संपर्क क्रमांक",
    businessType: "व्यवसाय प्रकार",
    gstNumber: "GST क्रमांक",
    establishmentYear: "स्थापना वर्ष",
    established: "स्थापना",
    licenseNumber: "परवाना क्रमांक",
    license: "परवाना",
    businessAddress: "व्यवसाय पत्ता",
    specialization: "विशेषता",
    businessSettings: "व्यवसाय सेटिंग्स",
    paymentMethods: "पेमेंट पद्धती",
    manageAcceptedPayments: "स्वीकृत पेमेंट पद्धती व्यवस्थापित करा",
    deliverySettings: "डिलिव्हरी सेटिंग्स",
    configureDeliveryLogistics: "डिलिव्हरी आणि लॉजिस्टिक्स कॉन्फिगर करा",
    configure: "कॉन्फिगर",
    setup: "सेटअप",
    tradeAreas: "व्यापार क्षेत्र",
    activeSuppliers: "सक्रिय पुरवठादार",
    monthlyOrders: "मासिक ऑर्डर",
    satisfaction: "समाधान",
    premiumPartner: "प्रीमियम पार्टनर",
    saveProfile: "प्रोफाइल सेव करा",
    wholesaleDistributor: "घाऊक वितरक",
    grains: "धान्य",
    vegetables: "भाज्या",
    cashCrops: "नगदी पिके",
    mySuppliers: "माझे पुरवठादार",
    manageSuppliers: "ज्या शेतकऱ्यांशी तुम्ही डील किंवा विनंती केली आहे",
    addNewSupplier: "नवीन पुरवठादार जोडा",
    totalSuppliers: "एकूण पुरवठादार",
    totalValue: "एकूण मूल्य",
    searchSuppliers: "नाव किंवा स्थानानुसार पुरवठादार शोधा...",
    allStatus: "सर्व स्थिती",
    inactive: "निष्क्रिय",
    mainCrops: "मुख्य पिके",
    reliability: "विश्वसनीयता",
    contact: "संपर्क",
    orderNow: "ऑर्डर करा",
    noSuppliersYet: "अजून कोणताही पुरवठादार नाही",
    noMatchingSuppliers: "जुळणारे पुरवठादार नाहीत",
    clearSearch: "शोध साफ करा",
    goToMarketplace: "मार्केटप्लेसवर जा",
    businessAnalytics: "व्यवसाय विश्लेषण",
    realTimeInsights: "तुमच्या डीलरशिपच्या कामगिरीबद्दल रिअल-टाइम माहिती",
    lastMonth: "मागील महिना",
    totalSpentLabel: "एकूण खर्च",
    completedDeals: "पूर्ण डील",
    farmersSourced: "शेतकरी स्रोत",
    totalRequests: "एकूण विनंत्या",
    monthlySpending: "मासिक खर्च",
    last6Months: "मागील 6 महिने",
    topCropsPurchased: "सर्वाधिक खरेदी केलेली पिके",
    requestStatus: "विनंती स्थिती",
    businessInsights: "व्यवसाय अंतर्दृष्टी",
    topPurchaseInsight: "गहू तुमची सर्वाधिक खरेदी आहे",
    topPurchaseText: "₹1,25,000 गव्हावर खर्च",
    farmersInsight: "12 वेगवेगळे शेतकरी स्रोत",
    farmersInsightText: "चांगली पुरवठादार विविधता! वाढवत ठेवा",
    pendingPaymentInsight: "₹18,000 प्रलंबित पेमेंट",
    pendingPaymentText: "शेतकऱ्यांचा विश्वास वाढवण्यासाठी पेमेंट करा",
    activeDealsInsight: "4 सक्रिय डील सुरू आहेत",
    activeDealsText: "सक्रिय डीलची डिलिव्हरी ट्रॅक करा",
    pendingPayments: "प्रलंबित पेमेंट",
    dealsCompleted: "पूर्ण डील",
    purchaseOrders: "खरेदी ऑर्डर",
    trackManageOrders: "तुमचे सर्व खरेदी ऑर्डर ट्रॅक आणि व्यवस्थापित करा",
    newOrder: "नवीन ऑर्डर",
    delivered: "वितरित",
    processing: "प्रक्रिया सुरू",
    inTransit: "वाहतुकीत",
    searchOrders: "ऑर्डर आयडी, पुरवठादार किंवा पीक शोधा...",
    allOrders: "सर्व ऑर्डर",
    filter: "फिल्टर",
    orderDetails: "ऑर्डर तपशील",
    supplier: "पुरवठादार",
    amount: "रक्कम",
    status: "स्थिती",
    actions: "क्रिया",
    paymentPaid: "पेमेंट पूर्ण",
    paymentPending: "पेमेंट प्रलंबित",
    paymentPartial: "आंशिक पेमेंट",
    paymentRefunded: "पेमेंट परत",
    needHelp: "मदत हवी आहे?",
    contactSupportText: "ऑर्डर संबंधित प्रश्नांसाठी सपोर्टशी संपर्क करा",
    contactSupport: "सपोर्टशी संपर्क",
    exportData: "डेटा निर्यात",
    downloadReports: "ऑर्डर रिपोर्ट आणि इनव्हॉइस डाउनलोड करा",
    exportOrders: "ऑर्डर निर्यात करा",
    orderSummary: "ऑर्डर सारांश",
    avgOrder: "सरासरी ऑर्डर",
    cropMarketplace: "पीक मार्केटप्लेस",
    farmersBrowseCrops: "शेतकरी खरी पिके पाहू शकतात आणि विनंती पाठवू शकतात",
    cropsAvailable: "पिके उपलब्ध",
    searchCropFarmerLocation: "पीक, शेतकरी, स्थान शोधा...",
    allCrops: "सर्व पिके",
    noCropsListed: "अजून कोणत्याही शेतकऱ्याने पीक सूचीबद्ध केलेले नाही",
    farmersLoginAddCrops: "शेतकरी लॉगिन करून My Crops मधून पिके जोडू शकतात",
    marketplaceTips: "मार्केटप्लेस टिप्स",
    requestSend: "विनंती पाठवा",
    farmerAcceptDeal: "शेतकरी स्वीकारल्यावर डील तयार होईल",
    negotiate: "चर्चा करा",
    negotiatePrice: "तुम्ही किंमत चर्चा करू शकता",
    trackRequest: "विनंती ट्रॅक करा",
    trackOrders: "Orders पेजवरून विनंत्या ट्रॅक करा",
    dealerDashboard: "डीलर डॅशबोर्ड",
    welcomeDealerOverview: "परत स्वागत आहे! हा तुमच्या व्यवसायाचा आढावा आहे",
    monthlyRevenue: "मासिक उत्पन्न",
    inventoryValue: "इन्व्हेंटरी मूल्य",
    orderId: "ऑर्डर आयडी",
    topSuppliers: "शीर्ष पुरवठादार",
    viewAllSuppliers: "सर्व पुरवठादार पहा",
    placeNewOrder: "नवीन ऑर्डर करा",
    findQualityCrops: "शेतकऱ्यांकडून चांगली पिके शोधा",
    browseMarketplace: "मार्केटप्लेस पहा",
    trackInventory: "इन्व्हेंटरी ट्रॅक करा",
    manageStockLevels: "तुमचे स्टॉक स्तर व्यवस्थापित करा",
    viewInventory: "इन्व्हेंटरी पहा",
    viewBusinessInsights: "व्यवसाय विश्लेषण पहा",
    viewReports: "अहवाल पहा",
    openAgriAssist: "एग्रीअसिस्ट उघडा",
    export: "निर्यात करा",
    activeSchemes: "सक्रिय योजना",
    governmentSchemes: "सरकारी योजना",
    browseAndApplyForSchemesDesignedForFarmers: "शेतकऱ्यांसाठी तयार केलेल्या योजनांचा शोध घ्या आणि अर्ज करा",
    live: "लाईव्ह",
    schemesCount: "26 योजना",
    searchSchemesByNameCropEligibility: "नाव, पीक किंवा पात्रतेनुसार योजना शोधा...",
    allSchemes: "सर्व योजना",
    newScheme: "नवीन योजना",
    insurance: "विमा",
    creditLoans: "कर्ज / कर्ज सुविधा",
    irrigation: "सिंचन",
    cropSpecific: "विशिष्ट पीक",
    infrastructure: "पायाभूत सुविधा",
    machinery: "यंत्रसामग्री",
    marketMSP: "बाजार / एमएसपी",
    pension: "पेन्शन",
    alliedSectors: "संबंधित क्षेत्र",
    foodProcessing: "अन्न प्रक्रिया",
    mspSupport: "एमएसपी समर्थन",
    soilTesting: "माती परीक्षण",
    dealsAndPayments: "डील्स आणि पेमेंट्स",
    manageYourDealsAndTrackAllTransactions: "तुमच्या डील्स व्यवस्थापित करा आणि सर्व व्यवहार ट्रॅक करा",
    makePayment: "पेमेंट करा",
    moneyReceived: "मिळालेले पैसे",
    activeDeals: "सक्रिय डील्स",
    dealRevenue: "डील उत्पन्न",
    myDeals: "माझ्या डील्स",
    payment: "पेमेंट",
    noDealsFound: "कोणतीही डील सापडली नाही",
    tryAdjustingYourFilters: "तुमचे फिल्टर समायोजित करून पाहा",
    searchByCropOrDealer: "पीक किंवा व्यापाऱ्यानुसार शोधा",
    noRequestsFound: "कोणत्याही विनंत्या सापडल्या नाहीत",
    whenDealersShowInterestInYourCropsTheyWillAppearHere: "जेव्हा व्यापारी तुमच्या पिकांमध्ये रस दाखवतात तेव्हा ते येथे दिसतील",
    quickTips: "💡 जलद टिप्स",
    checkDealerRatings: "व्यापारी रेटिंग तपासा",
    alwaysVerifyDealerCredibilityBeforeAccepting: "स्वीकारण्यापूर्वी व्यापाऱ्याची विश्वासार्हता नेहमी तपासा",
    negotiateSmartly: "हुशारीने वाटाघाटी करा",
    compareWithMarketPricesBeforeCountering: "काउंटर करण्यापूर्वी बाजारभावाशी तुलना करा",
    reviewDeliveryTerms: "डिलिव्हरी अटींचे पुनरावलोकन करा",
    ensureDeliveryDatesAndLogisticsAreClear: "डिलिव्हरी तारखा आणि लॉजिस्टिक्स स्पष्ट असल्याची खात्री करा",
    realTimeCropPricesAndMarketTrends: "रिअल-टाइम पिकांचे दर आणि बाजारातील प्रवृत्ती",
    low: "कमी",
    totalCropsTracked: "एकूण ट्रॅक केलेली पिके",
    demand: "मागणी",
    markets: "बाजार",
    highestPrice: "सर्वाधिक किंमत",
    avgPriceChange: "सरासरी किंमत बदल",
    allRegions: "सर्व प्रदेश",
    allCategories: "सर्व श्रेणी",
    trending: "ट्रेंडिंग",
    highDemand: "जास्त मागणी",
    cropDetails: "पिकाची माहिती",
    currentPrice: "सध्याची किंमत",
    marketAndRegion: "बाजार आणि प्रदेश",
    trendPrediction: "ट्रेंड अंदाज",
    veryHigh: "खूप जास्त",
    high: "जास्त",
    medium: "मध्यम",
    stable: "स्थिर",
    bullish: "बुलिश",
    growing: "वाढत आहे",
    rising: "वाढत आहे",
    seasonal: "हंगामी",
    declining: "घटत आहे",
    addyourfirstcrop: "तुमचे पहिले पीक जोडा",
    tryadjustingyoursearchoraddanewcrop: "तुमचा शोध अ‍ॅडजस्ट करून पहा किंवा नवीन क्रॉप जोडा",
    nocropsfound: "कोणतीही पिके आढळली नाहीत",
    sold: "विक्री",
    available: "उपलब्ध",
    manageyourcropinventoryandlistings: "तुमची पीक यादी आणि सूची व्यवस्थापित करा",
    searchcropsbynameorcategory: "नाव किंवा श्रेणीनुसार पिके शोधा...",
    totalCrop: "एकूण पीक",
    addNewCrops: "नवीन पिके जोडा",
    norecentactivityyet: "अद्याप कोणतीही अलीकडील क्रियाकलाप नाही",
    pendingRequests1: "प्रलंबित विनंत्या",
    recentActivity: "अलीकडील क्रियाकलाप",
    agriAssist: "कृषी सहाय्य",
    marketPrice: "बाजारभाव",
    manageCrops: "पिके व्यवस्थापित करा",
    buyers: "खरेदीदार",
    welcomeback: "परत स्वागत आहे",

    // ── App General ──────────────────────────────────────────────────
    dashboard: "डॅशबोर्ड",
    appName: "एग्री कनेक्ट",
    login: "लॉगिन",
    register: "नोंदणी",
    logout: "लॉगआउट",
    getStarted: "सुरू करा",
    learnMore: "अधिक जाणून घ्या",
    whyChooseUs: "एग्री कनेक्ट का निवडावे?",
    directConnection: "थेट संपर्क",
    directConnectionDesc: "मध्यस्थ काढून शेतकऱ्यांना डीलर्सशी थेट जोडा",
    marketPricesDesc: "माहितीपूर्ण निर्णयांसाठी रिअल-टाइम बाजार भाव आणि ट्रेंड",
    community: "समुदाय",
    communityDesc: "शेतकरी आणि डीलर्सच्या भरभराट समुदायात सामील व्हा",
    secure: "सुरक्षित प्लॅटफॉर्म",
    secureDesc: "सत्यापित वापरकर्त्यांसह सुरक्षित व्यवहार",
    readyToStart: "व्यापार सुरू करण्यास तयार आहात?",
    joinThousands: "आमच्या प्लॅटफॉर्मवर आधीच असलेल्या हजारो शेतकरी आणि डीलर्समध्ये सामील व्हा",
    registerNow: "आता नोंदणी करा",
    allRightsReserved: "सर्व हक्क राखीव.",
    myCrops: "माझी पिके",
    marketplace: "बाजार",
    orders: "ऑर्डर्स",
    suppliers: "पुरवठादार",
    schemes: "सरकारी योजना",
    advisor: "एआय सल्लागार",
    requests: "विनंत्या",
    users: "वापरकर्ते",
    analytics: "विश्लेषण",
    profile: "प्रोफाइल",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्डची पुष्टी करा",
    name: "पूर्ण नाव",
    loginAs: "म्हणून लॉगिन करा",
    registerAs: "म्हणून नोंदणी करा",
    dealer: "व्यापारी",
    government: "सरकार",
    admin: "प्रशासक",
    dontHaveAccount: "खाते नाही?",
    alreadyHaveAccount: "आधीच खाते आहे?",
    backToHome: "होमवर परत जा",
    welcomeBack: "परत आपले स्वागत आहे!",
    totalRevenue: "एकूण उत्पन्न",
    inventory: "इन्व्हेंटरी आयटम",
    welcomeDealer: "परत आपले स्वागत आहे! हा आपल्या व्यवसायाचा आढावा आहे।",
    farmers: "शेतकरी",
    dealers: "व्यापारी",
    districts: "जिल्हे",
    helpTitle:        "मदत आणि मार्गदर्शन",
    helpBtn:          "मदत",
    helpContact:      "अधिक मदत हवी? संपर्क करा support@agriconnect.in",
    helpIntro:        "Agri Connect ची ओळख",
    helpIntroDes:     "आमच्या प्लॅटफॉर्मबद्दल जाणून घ्या",
    helpLogin:        "लॉगिन प्रक्रिया",
    helpLoginDes:     "तुमच्या खात्यात कसे लॉगिन करावे",
    helpRegister:     "नोंदणी प्रक्रिया",
    helpRegDes:       "नवीन खाते तयार करा",
    helpFarmer:       "शेतकरी पॅनल",
    helpFarmerDes:    "शेतकऱ्यांसाठी मार्गदर्शन",
    helpDealer:       "व्यापारी पॅनल",
    helpDealerDes:    "व्यापाऱ्यांसाठी मार्गदर्शन",
    helpCustomer:     "ग्राहक पॅनल",
    helpCustomerDes:  "ग्राहकांसाठी मार्गदर्शन",
    trade: "व्यापार",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("en");
  const t = translations[language];
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};